# BLOCK & DISK CONSTANTS
NUM_BLOCKS = 16
BLOCK_SIZE = 64
DISK_NAME = 'my-disk'
ROOT_LOC = 0

# FILE METADATA SIZES
NEXT_FILE_SIZE = 1
NEXT_BLOCK_SIZE = 1
FILE_DATA_SIZE = 37

# EFFECTIVE SIZE
EFFECTIVE_BLOCK_SIZE = BLOCK_SIZE - NEXT_BLOCK_SIZE - NEXT_FILE_SIZE

# FILE METADATA LOCATIONS
NEXT_FILE_LOC = 0
NEXT_BLOCK_LOC = 1
FILE_DATA_LOC = 2

# STATS SIZE CONSTANTS
ST_MODE_SIZE = 2
ST_UID_SIZE = 2
ST_GID_SIZE = 2
ST_NLINKS_SIZE = 1
ST_SIZE_SIZE = 2
ST_CTIME_SIZE = 4
ST_MTIME_SIZE = 4
ST_ATIME_SIZE = 4
NAME_SIZE = 16

# STATS LOCATION CONSTANTS
MTIME_LOC = 13 + FILE_DATA_LOC
ATIME_LOC = 17 + FILE_DATA_LOC
NAME_LOC = FILE_DATA_LOC + FILE_DATA_SIZE - NAME_SIZE
ST_SIZE_LOC = 7 
ST_N_LINKS_LOC = FILE_DATA_LOC + 6

# ROOT METADATA SIZES
FH_SIZE = 1

# ROOT METADATA LOCATIONS
FH_LOC = 39